# Generated by Django 5.2.8 on 2025-12-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_comment_options_alter_rating_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('article', 'Стаття'), ('breaking_news', 'Термінова новина')], default='article', max_length=20, verbose_name='Type'),
        ),
    ]
