# Generated by Django 5.2.8 on 2025-12-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_publication_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('article', 'Article'), ('breaking_news', 'Breaking_News')], default='article', max_length=20, verbose_name='Type'),
        ),
    ]
