# Generated by Django 5.2.8 on 2025-12-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsettings',
            options={'verbose_name': 'Global System Setting', 'verbose_name_plural': 'Global System Settings'},
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='base_subscription_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6, verbose_name='Base Subscription Price'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='Maintenance Mode'),
        ),
    ]
