# Generated by Django 5.2.8 on 2025-12-14 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('price_mode', models.CharField(choices=[('fixed', 'Fixed Price (UAH)'), ('percentage', 'Percentage of Base')], default='fixed', max_length=20, verbose_name='Pricing Mode')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Value (Price or %)')),
                ('duration_days', models.IntegerField(default=30, verbose_name='Duration (days)')),
                ('strategy_type', models.CharField(choices=[('student', 'Student Logic'), ('corporate', 'Corporate Logic'), ('premium', 'Premium Logic')], default='premium', max_length=20, verbose_name='Strategy Type')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='Selected Plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
    ]
