# Generated by Django 5.2.8 on 2025-12-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_comment_rating'),
        ('users', '0003_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='content.publication', verbose_name='Bookmarks'),
        ),
    ]
